# Label Encoding

### What is  Nominal Data

In [3]:
# Categorical ===> 1. Nominal Data  2. Ordinal Data



In [5]:
# one hot encoding
# Nominal Data ==> Gender-> male,female
#                  color--> red,black
#                  city--> jiapur,goa

In [9]:
# odinal encoding
# movie rating,education label , customer satisfaction,dress size->s,m,l,xl,xxl etc

In [11]:
import numpy as np
import pandas as pd


In [15]:
df=pd.DataFrame({"name":["regex","rahul","jatin","sumit","suman"]})
df

name
0  regex
1  rahul
2  jatin
3  sumit
4  suman

In [17]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le=LabelEncoder()
le.fit_transform(df["name"])
# yah hamre nomial data ka encoding kr ke deta hai

array([2, 1, 0, 4, 3])

In [21]:
df["new name"]=le.fit_transform(df["name"])
df

name  new name
0  regex         2
1  rahul         1
2  jatin         0
3  sumit         4
4  suman         3

In [29]:
dataset=pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Desktop\\pandas\\covid_toy.csv")
dataset.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       NaN
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [31]:
la=LabelEncoder()
la.fit(dataset["city"])

LabelEncoder()

In [33]:
la.transform(dataset["city"])

array([2, 1, 1, 2, 3, 0, 0, 3, 4, 1, 1, 3, 2, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       2, 1, 2, 3, 2, 1, 2, 3, 4, 2, 1, 2, 3, 0, 0, 2, 1, 2, 1, 2, 1, 0,
       1, 4, 3, 0, 0, 3, 1, 2, 0, 1, 3, 3, 2, 0, 3, 2, 0, 3, 0, 0, 3, 0,
       2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 0, 2, 0, 2, 3, 1, 2, 2, 3, 0, 0, 0,
       2, 0, 1, 1, 2, 2, 2, 0, 2, 0, 3, 2])

In [35]:
dataset["city"].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore', nan], dtype=object)

In [39]:
dataset["city"]=la.transform(dataset["city"])

In [43]:
dataset["city"].unique()
# ab change ho gye hai

array([2, 1, 3, 0, 4])

In [47]:
dataset.head(5)

age  gender  fever cough  city has_covid
0   60    Male  103.0  Mild     2        No
1   27    Male  100.0  Mild     1       NaN
2   42    Male  101.0  Mild     1        No
3   31  Female   98.0  Mild     2        No
4   65  Female  101.0  Mild     3        No

# Ordinal Encoding

In [50]:
 # ordinal encoding two perfimes
# 1. sklearn
# 2. Map function

In [52]:
import pandas as pd

In [58]:
df=pd.DataFrame({"size":["s","m","xl","l","s","m","xxl","s","m","l"]})
df

size
0    s
1    m
2   xl
3    l
4    s
5    m
6  xxl
7    s
8    m
9    l

In [70]:
data=[["s","m","l","xl","xxl"]]

### 1. from by Sklearn

In [62]:
from sklearn.preprocessing import OrdinalEncoder

In [72]:
oe=OrdinalEncoder(categories=data)
oe.fit(df[["size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl', 'xxl']])

In [74]:
oe.transform(df[["size"]])

array([[0.],
       [1.],
       [3.],
       [2.],
       [0.],
       [1.],
       [4.],
       [0.],
       [1.],
       [2.]])

In [76]:
df["shape"]=oe.transform(df[["size"]])

In [78]:
df

size  shape
0    s    0.0
1    m    1.0
2   xl    3.0
3    l    2.0
4    s    0.0
5    m    1.0
6  xxl    4.0
7    s    0.0
8    m    1.0
9    l    2.0

In [92]:
oe=OrdinalEncoder(categories="auto")
oe.fit(df[["size"]])
# yah alphabet ke order se encoding krta hai

OrdinalEncoder()

In [86]:
oe.transform(df[["size"]])

array([[2.],
       [1.],
       [3.],
       [0.],
       [2.],
       [1.],
       [4.],
       [2.],
       [1.],
       [0.]])

In [88]:
df["shape"]=oe.transform(df[["size"]])

In [90]:
df

size  shape
0    s    2.0
1    m    1.0
2   xl    3.0
3    l    0.0
4    s    2.0
5    m    1.0
6  xxl    4.0
7    s    2.0
8    m    1.0
9    l    0.0

### 2. From by Map Function  

In [100]:
df=pd.DataFrame({"size":["s","m","xl","l","s","m","xxl","s","m","l"]})
df



size
0    s
1    m
2   xl
3    l
4    s
5    m
6  xxl
7    s
8    m
9    l

In [112]:
new={"s":0,"m":1,"l":2,"xl":3,"xxl":5000}

In [114]:
df["size"].map(new)

0       0
1       1
2       3
3       2
4       0
5       1
6    5000
7       0
8       1
9       2
Name: size, dtype: int64

In [116]:
df["new_size"]=df["size"].map(new)

In [118]:
df

size  new_size
0    s         0
1    m         1
2   xl         3
3    l         2
4    s         0
5    m         1
6  xxl      5000
7    s         0
8    m         1
9    l         2

In [120]:
  dataset=pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Desktop\\pandas\\covid_toy.csv")
dataset.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       NaN
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [122]:
dataset["city"].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore', nan], dtype=object)

In [126]:
dataset["city"].fillna(dataset["city"].mode()[0],inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10556\2665203789.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["city"].fillna(dataset["city"].mode()[0],inplace=True)


In [128]:
dataset["city"].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [130]:
new_odr_ofcity=[["Kolkata", "Delhi", "Mumbai", "Bangalore"]]

In [132]:
from sklearn.preprocessing import OrdinalEncoder

In [134]:
oen=OrdinalEncoder(categories=new_odr_ofcity)

In [138]:
oen.fit_transform(dataset[["city"]])

array([[0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [3.],
       [3.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [3.],
       [3.],
       [0.],
       [0.],
       [1.],
       [3.],
       [3.],
       [3.],
       [3.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [2.],
       [3.],
       [3.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [3.],
       [1.],
       [0.],
       [2.],
       [3.],
       [3.],
       [2.],
       [1.],
       [0.],
       [3.],
       [1.],
       [2.],
       [2.],
       [0.],
       [3.],
       [2.],
       [0.],
       [3.],
       [2.],
       [3.],
       [3.],
       [2.],
       [3.],
       [0.],
       [3.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [3.],

In [140]:
dataset["city"]=oen.fit_transform(dataset[["city"]])

In [142]:
dataset.head(10)

age  gender  fever   cough  city has_covid
0   60    Male  103.0    Mild   0.0        No
1   27    Male  100.0    Mild   1.0       NaN
2   42    Male  101.0    Mild   1.0        No
3   31  Female   98.0    Mild   0.0        No
4   65  Female  101.0    Mild   2.0        No
5   84  Female    NaN    Mild   3.0       Yes
6   14    Male  101.0  Strong   3.0        No
7   20  Female    NaN  Strong   2.0       Yes
8   19  Female  100.0  Strong   0.0        No
9   64  Female  101.0    Mild   1.0        No