In [133]:
import numpy as np
import pandas as pd

In [135]:
df=pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Desktop\\pandas\\customer.csv")


In [137]:
df.sample(5)

age  gender review education purchased
25   57  Female   Good    School        No
35   74    Male   Poor    School       Yes
41   23    Male   Good        PG       Yes
28   48    Male   Poor    School        No
26   53  Female   Poor        PG        No

In [139]:
df=df.iloc[:,2:]

In [141]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [143]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [145]:
from sklearn.preprocessing import OrdinalEncoder

In [147]:
x_train

review education
33     Good        PG
6      Good    School
18     Good    School
43     Poor        PG
11     Good        UG
29  Average        UG
47     Good        PG
39     Poor        PG
35     Poor    School
2      Good        PG
17     Poor        UG
1      Poor        UG
25     Good    School
48     Good        UG
0   Average    School
24  Average        PG
30  Average        UG
38     Good    School
23     Good    School
7      Poor    School
8   Average        UG
45     Poor        PG
37  Average        PG
49     Good        UG
16     Poor        UG
41     Good        PG
20  Average    School
4   Average        UG
22     Poor        PG
46     Poor        PG
21  Average        PG
31     Poor    School
44  Average        UG
42     Good        PG
40     Good    School
36     Good        UG
5   Average    School
15     Poor        UG
27     Poor        PG
19     Poor        PG

In [149]:
x_test

review education
26     Poor        PG
10     Good        UG
13  Average    School
34  Average    School
12     Poor    School
9      Good        UG
3      Good        PG
28     Poor    School
14     Poor        PG
32  Average        UG

In [151]:
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [153]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [155]:
x_train=oe.transform(x_train)


In [157]:
x_test=oe.transform(x_test)

In [159]:
x_train

array([[2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.]])

In [161]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [163]:
x_train

array([[2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.]])

In [165]:
from sklearn.preprocessing import LabelEncoder 

In [167]:
le=LabelEncoder()

In [169]:
le.fit(y_train)

LabelEncoder()

In [171]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [178]:

y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [180]:
y_train

array([1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1])